### ISSUE TITLE
Is it possible to use state elsewhere?

### ISSUE THREAD

**Issue by Baiyuetribe** [viz-rs/viz#103]
The following code works fine, 
```rust
pub type Counter = Arc<Mutex<u32>>; 
async fn demo(mut req: Request) -> Result<Response> {
    let State(counter) = req.extract::<State<Counter>>().await?;
    let mut counter = counter.lock().unwrap();
    *counter += 1;
    Ok(Response::text(format!("Hello, World!{}", counter)))
}
```
but it's an exception when it's called from somewhere else
```rust
// no args
async fn demo() {
    let mut req = Request::builder().body(IncomingBody::Empty).unwrap();
    let State(counter) = req.extract::<State<Counter>>().await.unwrap();
    let mut counter = counter.lock().unwrap();
    *counter += 1;
    println!("Hello, World!{}", counter)
}
```
erros:
missing state type `alloc::sync::Arc<std::sync::mutex::Mutex<u32>>`

**Comment by fundon** [comment]
Do you have the complete code?

**Comment by Baiyuetribe** [comment]
https://github.com/viz-rs/viz/blob/24f224fb45a820e2f8b6cb0c6ed735f42609fc88/examples/routing/todos/src/main.rs#L74

modify this method:
```rust
async fn show(_: Request) -> Result<Response> {
    let mut req = Request::builder().body(IncomingBody::Empty).unwrap();
    let State(db) = req.extract::<State<DB>>().await?;
    let _ = db.lock();
    println!("print if db is ok");
    Ok(Response::text("Hello, World!"))
}

```
`cargo run --bin todos`
try : http://127.0.0.1:3000/todos/1

**Comment by fundon** [comment]
@Baiyuetribe 

It's correct. In original, the `DB` state is added into the `request`:

https://github.com/viz-rs/viz/blob/24f224fb45a820e2f8b6cb0c6ed735f42609fc88/examples/routing/todos/src/main.rs#L137

**Comment by Baiyuetribe** [comment]
@fundon no,it not work

> https://github.com/viz-rs/viz/blob/24f224fb45a820e2f8b6cb0c6ed735f42609fc88/examples/routing/todos/src/main.rs#L74
> 
> modify this method:
> 
> ```rust
> async fn show(_: Request) -> Result<Response> {
>     let mut req = Request::builder().body(IncomingBody::Empty).unwrap();
>     let State(db) = req.extract::<State<DB>>().await?; // ***erorr***
>     let _ = db.lock();
>     println!("print if db is ok");
>     Ok(Response::text("Hello, World!"))
> }
> ```
> 
> `cargo run --bin todos` try : http://127.0.0.1:3000/todos/1
