### ISSUE TITLE
[BUG]Error while serving HTTP connection: early eof

### ISSUE THREAD

**Issue by Baiyuetribe** [viz-rs/viz#104]
##  Reproduce
https://github.com/viz-rs/viz/blob/main/examples/static-files/embed/src/main.rsv
add `a.txt` file to `public` dir. this file with some word,size 1kb or more.
`cargo run --bin embed`
run this demo, then quick request url. It will cause a reboot `serve`
`http://127.0.0.1:3000/static/a.txt`

## Logs
```log
Error while serving HTTP connection: early eof
Error while serving HTTP connection: early eof
```

## Expectations
This bug should not occur in the main application, as it will cause other connections that are being requested to fail

**Comment by Baiyuetribe** [comment]
both of `embed` and `serve`  will trigger this error. 
- `embed` is a small probability of occurrence
- 100 per cent failure in `serve` mode
https://github.com/viz-rs/viz/blob/main/examples/static-files/serve/src/main.rs

**Comment by fundon** [comment]
Can you help with the test? 
The commit is https://github.com/viz-rs/viz/commit/df8deecf5d6b0fbd3b4bb4e3a2b78816e6ecc1bc

**Comment by Baiyuetribe** [comment]
@fundon This fault has come up.
After we have made several requests in a row, wait about 1 minute and it will be reproduced when refreshed

**Comment by Baiyuetribe** [comment]
##  Reproduce
https://github.com/viz-rs/viz/blob/main/examples/static-files/embed/src/main.rsv
add `a.txt` file to `public` dir. this file with some word,size 1kb or more.
`cargo run --bin embed`
run this demo,
`http://127.0.0.1:3000/static/a.txt`

After the first request, wait one minute to request again
