### ISSUE TITLE
How good is the web-socket support?

### ISSUE THREAD

**Issue by ishtms** [viz-rs/viz#37]
Hi, Viz seems like a very good and a minimal alternative to all others out there. I have a question, is the websocket support fully-featured? How does it compare to something like [tokio-tungstenite](https://github.com/snapview/tokio-tungstenite)? 

I'd love to use Viz it in a personal project to try it out.

**Comment by fundon** [comment]
Supported, example is [here](https://github.com/viz-rs/viz/tree/main/examples/websocket-chat).

**Comment by fundon** [comment]
Welcome any suggestions. :)

**Comment by fundon** [comment]
See https://github.com/viz-rs/viz/blob/main/viz-core/Cargo.toml#L69. We use tokio-tungstenite for websockets.
