### ISSUE TITLE
Default for viz::types::State?

### ISSUE THREAD

**Issue by crwn1337** [viz-rs/viz#79]
would be nice to have `Default` for State so instead of having this horrible mess:
```rust
let state = State::new(Arc::new(AppState::default()));
```
i could instead have this less horrible mess:
```rust
type SharedAppState = State<Arc<AppState>>;
let state = SharedAppState::default();
```

**Comment by fundon** [comment]
Good idea.

**Comment by fundon** [comment]
Landed in https://github.com/viz-rs/viz/releases/tag/v0.4.10. 

Also landed in `main` branch.
