### ISSUE TITLE
no `serve` in the root

### ISSUE THREAD

**Issue by Baiyuetribe** [viz-rs/viz#98]
```rust

use std::{net::SocketAddr, sync::Arc};
use tokio::net::TcpListener;
use viz::{serve, Request, Result, Router, Tree};

async fn index(_: Request) -> Result<&'static str> {
    Ok("Hello, World!")
}

#[tokio::main]
async fn main() -> Result<()> {
    let addr = SocketAddr::from(([127, 0, 0, 1], 3000));
    let listener = TcpListener::bind(addr).await?;
    println!("listening on http://{addr}");

    let app = Router::new().get("/", index);
    let tree = Arc::new(Tree::from(app));

    loop {
        let (stream, addr) = listener.accept().await?;
        let tree = tree.clone();
        tokio::task::spawn(serve(stream, tree, Some(addr)));
    }
}
```
The hello-word above won't run. error[E0432]: unresolved import `viz::serve`

**Comment by Baiyuetribe** [comment]
```rust
    if let Err(err) = Server::bind(&addr).serve(ServiceMaker::from(app)).await {
        println!("{err}");
    }
```
I also found this works, is it equal to the implementation above?

**Comment by Baiyuetribe** [comment]
is `v0.4.x` can not use State? i test some state,like
![image](https://github.com/viz-rs/viz/assets/43716063/289144c5-3d54-447f-b057-3e26e034d767)
```log
missing state type `alloc::sync::Arc<std::sync::mutex::Mutex<alloc::vec::Vec<leaf::router::Todo>>>`
```

**Comment by fundon** [comment]
The `sea_orm` example was added to `main`, and the `main` branch is `v0.5.x`.

I checked it. The `todos` example works ok.

```console
git switch 0.4.x
cd examples
cargo run --bin todos -- --nocapture
```

BTW, it also works fine in `main` branch.

**Comment by fundon** [comment]
Maybe you need to add those:

https://github.com/viz-rs/viz/blob/3d1e46dc1976caa1836eb320df06954e29eeb79d/examples/routing/todos/src/main.rs#L17-L18

**Comment by Baiyuetribe** [comment]
yes, it only works with the main branch.
but if you use `cargo add viz` in your own project. it faild.  looking forward to v0.5.x release

**Comment by fundon** [comment]
@Baiyuetribe

See [specifying-dependencies-from-git-repositories](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-git-repositories)

```
[dependencies]
viz  = { git = "https://github.com/viz-rs/viz.git", branch = "main" }
```

**Comment by fundon** [comment]
0.5.0 is released.
